cluster:
  # specify cluster labels
  labels: 
    cluster-provisionning: 'fleet'

cloudprovider: amazonec2

# enable monitoring
monitoring:
  enabled: true

# general RKE options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false  

  machineGlobalConfig:
    cni: canal
