kubernetesVersion: v1.26.13+rke2r1

cluster:
  # specify cluster labels
  labels: 
    cluster-provisionning: 'fleet'

# enable monitoring
monitoring:
  enabled: true

# general RKE options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false  

  machineGlobalConfig:
    cni: canal
