cluster:
  # specify cluster labels
  labels: 
    cluster-provisionning: 'fleet'

cloudprovider: amazonec2

# enable monitoring
monitoring:
  enabled: true

# general RKE options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false  

  machineGlobalConfig:
    cni: canal

# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:
  - etcd: true
    controlplane: true
    worker: false

    # specify nodepool size
    quantity: 1

    # specify nodepool name
    name: controlplane

    instanceType: t3a.medium
    # Set retry count for recoverable failures (use -1 to disable)
    retries: 5
    # AWS root disk size (in GB)
    rootSize: 16

    # Set the name of the ssh user
    sshUser: ubuntu
    # Amazon EBS volume type
    volumeType: gp2

    vpcId: ''
    subnetId: ''
    region: eu-central-1
    zone: a
    createSecurityGroup: true

  - etcd: false
    controlplane: false
    worker: true

    # specify nodepool size
    quantity: 1

    # Pause node pool
    paused: false
  
    # specify nodepool name
    name: workers
    instanceType: t3a.medium

    # Set retry count for recoverable failures (use -1 to disable)
    retries: 5
    # AWS root disk size (in GB)
    rootSize: 16

    # Set the name of the ssh user
    sshUser: ubuntu
    # Amazon EBS volume type
    volumeType: gp2

    vpcId: ''
    subnetId: ''
    region: eu-central-1
    zone: a
    createSecurityGroup: true

